# Simple workflow for deploying static content to GitHub Pages
name: 部署一个vue项目

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: checkout 代码
        uses: actions/checkout@v4
      - name: 编译项目
        run: npm install && npm run build
      - name: 设置 pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
      - name: 上传文件到制品库
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './dist'
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
